#
# This file is part of the NML build framework
# NML build framework is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, version 2.
# NML build framework is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with NML build framework. If not, see <http://www.gnu.org/licenses/>.
#

# Definition of the grfs
REPO_NAME           ?= RIMS - Real International Maglev Set

# This is the filename part common to the grf file, main source file and the tar name
BASE_FILENAME       ?= RIMS

# Documentation files
DOC_FILES ?= docs/readme.txt docs/license.txt docs/changelog.txt

# NewGRF Version Settings
NEWGRF_VERSION      ?= 12
REPO_VERSION_STRING ?= 1.6.1
REPO_TITLE          ?= $(REPO_NAME) $(REPO_VERSION_STRING)

# Directory structure
SCRIPT_DIR          ?= scripts

# Uncomment in order to make use of gimp scripting. See the file
# for a description of the format
# GFX_SCRIPT_LIST_FILES      := gfx/png_source_list

# If needed, declare the minimum NML requirements
# REQUIRED_NML_BRANCH  = 0.4
# MIN_NML_REVISION     = 0